version: "2"
networks:
  app_bridge:
    driver: bridge
services:
  # nginx service - handles incoming requests to the server and forwards to app if applicable
  nginx:
    image: nginx
    container_name: nginx-container
    restart: always
    ports: 
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jeepee
    networks:
      - app_bridge
      
  # jeepee service - application, sits behind nginx and controls the pins, camera and monitoring modules
  jeepee:
    image: siouija/jeepee-dev
    container_name: jeepee-dev-container
    privileged: true # required so we can interact with the pins
    restart: always
    networks:
      - app_bridge